DB_NAME="SNDBX_DEMO_DB"
SCHEMA_NAME="DEMO_WORK_INTERIM"
DB_DICT={"SAND BOX":"SNDBX","DEV":"DEV","UAT":"UAT","PROD":"PRD"}
CLIENT_DB_DICT={"SAND BOX":"SNDBX_DEMO_DB","DEV":"DEV","UAT":"UAT","PROD":"PRD"}