[sf_usage_app]

[sf_db_schema]
DB_NAME="SNDBX_DEMO_DB"
SCHEMA_NAME="DEMO_WORK_INTERIM"

[snowflake1]
user = "VNDR_GRPVNDRFRACTAL"
password = "Charter@Fractal@2023"
account = "charter_daas"
warehouse = "WH_XL2_GRP_VNDR_FRACTAL"
database = "GRP_VNDR_FRACTAL"
schema = "GRPVNDRFRACTAL"
